
class Config(object):
    DEBUG = False

class TestConfig(Config):
    DEBUG = True

# ENV
# TESTING
# PROPAGATE_EXCEPTIONS
# PRESERVE_CONTEXT_ON_EXCEPTION
# TRAP_HTTP_EXCEPTIONS
# TRAP_BAD_REQUEST_ERRORS
# SECRET_KEY
# SESSION_COOKIE_NAME
# SESSION_COOKIE_DOMAIN
# SESSION_COOKIE_PATH
# SESSION_COOKIE_HTTPONLY
# SESSION_COOKIE_SECURE
# SESSION_COOKIE_SAMESITE
# PERMANENT_SESSION_LIFETIME
# SESSION_REFRESH_EACH_REQUEST
# USE_X_SENDFILE
# SEND_FILE_MAX_AGE_DEFAULT
# SERVER_NAME
# APPLICATION_ROOT
# PREFERRED_URL_SCHEME
# MAX_CONTENT_LENGTH
# JSON_AS_ASCII
# JSON_SORT_KEYS
# JSONIFY_PRETTYPRINT_REGULAR
# JSONIFY_MIMETYPE
# TEMPLATES_AUTO_RELOAD
# EXPLAIN_TEMPLATE_LOADING
# MAX_COOKIE_SIZE
